name: user_profile_app
description: A Flutter application for user profiles

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0         # For generating QR codes
  qr_code_scanner: ^1.0.1    # For scanning QR code



  # Firebase packages
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_database: ^11.3.5

  # UI & Utilities
  cupertino_icons: ^1.0.6
  flutter_slidable: ^4.0.0
  font_awesome_flutter: ^10.8.0
  fluttertoast: ^8.2.8
  get: ^4.6.5
  image_picker: ^1.1.2
  image: ^4.5.4
  url_launcher: ^6.2.2
  maps_launcher: ^3.0.0+1
  multiple_stream_builder: ^3.0.0


  # Authentication
  google_sign_in: ^6.3.0

  # Cloud Storage - USING OFFICIAL CLOUDINARY SDK
  cloudinary_dart: ^0.0.11
  cloudinary_flutter: ^0.0.1

  http: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  collection: ^1.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/login.png
    - assets/register.png

